# Generated by Django 5.0.7 on 2024-08-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=250, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Cart',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100, null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, null=True)),
                ('product_desc', models.TextField(max_length=100, null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_img', models.ImageField(null=True, upload_to='img/')),
                ('product_qty', models.IntegerField(null=True)),
                ('p_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcapp.product')),
            ],
            options={
                'db_table': 'CartItem',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_fname', models.CharField(max_length=30, null=True)),
                ('e_lname', models.CharField(max_length=30, null=True)),
                ('e_address', models.CharField(max_length=100, null=True)),
                ('e_phone_numbr', models.BigIntegerField(null=True, verbose_name=10)),
                ('e_email', models.EmailField(max_length=254, null=True)),
                ('e_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapp.category')),
                ('e_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='p_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapp.user'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50, null=True)),
                ('f_feed', models.CharField(max_length=100, null=True)),
                ('f_DOB', models.DateField(null=True)),
                ('f_status', models.CharField(max_length=30, null=True)),
                ('f_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fcapp.user')),
            ],
        ),
    ]
